repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
-   repo: local
    hooks:
    -   id: flake8
        name: flake files
        entry: flake8 task/ 
        language: python
        files: \.py$
        exclude: ^swagger/,__init__.py, ^venv/
    -   id: isort
        name: Sorting import statements
        entry: isort
        language: python
        args: ["--filter-files"]
        files: \.py$
        exclude: ^swagger/,__init__.py,^venv/
